#pragma once

// From glfw3.h

#define TOMOE_MOUSE_BUTTON_1         0
#define TOMOE_MOUSE_BUTTON_2         1
#define TOMOE_MOUSE_BUTTON_3         2
#define TOMOE_MOUSE_BUTTON_4         3
#define TOMOE_MOUSE_BUTTON_5         4
#define TOMOE_MOUSE_BUTTON_6         5
#define TOMOE_MOUSE_BUTTON_7         6
#define TOMOE_MOUSE_BUTTON_8         7
#define TOMOE_MOUSE_BUTTON_LAST      TOMOE_MOUSE_BUTTON_8
#define TOMOE_MOUSE_BUTTON_LEFT      TOMOE_MOUSE_BUTTON_1
#define TOMOE_MOUSE_BUTTON_RIGHT     TOMOE_MOUSE_BUTTON_2
#define TOMOE_MOUSE_BUTTON_MIDDLE    TOMOE_MOUSE_BUTTON_3